version: '3'

services:
  node-app:
    container_name: node-app-prod
    command:
      - /bin/bash
      - -c 
      - |
        npx prisma generate
        npx prisma migrate deploy
        npm run start
