version: '3'

services:
  node-app:
    container_name: node-app-dev
    command:
      - /bin/bash
      - -c 
      - |
        npx prisma generate
        npx prisma migrate dev
        npm run dev
