version: '3'

services:
  node-app:
    build: .
    image: node-app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/node-app
    networks:
      - node-network

  postgres:
    image: postgres:15.3-alpine3.18
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - node-network

volumes:
  pgdata:

networks:
  node-network:
    driver: bridge
